name: CI
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: cloud.libraryofcode.org
          username: internetramen
          password: ${{ secrets.PASS }}
          script: |
            whoami
            ls
